# config_raisonnement_logique.yaml
model:
  name: "camembert-base"  # Ou un modèle génératif comme GPT-2 français
  num_labels: 1  # Pour génération de texte, pas classification
  task_type: "text_generation"  # Nouvelle tâche

training:
  output_dir: "./finetuned/camembert-finetuned-raisonnement"
  num_train_epochs: 5  # Plus d'époques pour apprendre le raisonnement
  per_device_train_batch_size: 8  # Plus petit pour séquences longues
  per_device_eval_batch_size: 16
  warmup_steps: 1000
  weight_decay: 0.01
  logging_dir: "./logs/logs-raisonnement"
  logging_steps: 50
  eval_strategy: "steps"
  eval_steps: 200
  save_strategy: "steps"
  save_steps: 500
  load_best_model_at_end: true
  metric_for_best_model: "loss"  # Pour génération de texte
  seed: 42

tokenizer:
  max_length: 512  # Plus long pour les raisonnements complets
  truncation: true
  padding: "max_length"
  return_tensors: "pt"

data:
  test_size: 0.15
  random_state: 42
  stratify: false  # Pas de stratification pour génération

metrics:
  loss: true
  perplexity: true
